# TGL Medusa Loggers - Docker Compose for Local Development
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://tgl_user:tgl_password@db:5432/tgl_medusa_loggers
      - SECRET_KEY=dev-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - APP_NAME=TGL Medusa Loggers
      - DEBUG=true
      - ENVIRONMENT=development
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=tgl_medusa_loggers
      - POSTGRES_USER=tgl_user
      - POSTGRES_PASSWORD=tgl_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://tgl_user:tgl_password@db:5432/tgl_medusa_loggers
      - SECRET_KEY=dev-secret-key-change-in-production
      - APP_NAME=TGL Medusa Loggers
      - DEBUG=true
      - ENVIRONMENT=development
    depends_on:
      - db
    volumes:
      - .:/app
    command: python -c "
      import asyncio
      import time
      from main import monitor_instances
      
      async def worker_main():
          print('TGL Medusa Loggers Worker Starting...')
          while True:
              try:
                  await monitor_instances()
                  await asyncio.sleep(60)
              except Exception as e:
                  print(f'Worker error: {e}')
                  await asyncio.sleep(30)
      
      asyncio.run(worker_main())
      "

volumes:
  postgres_data:
