# Netlify configuration for TAR Global Strategies Static Site
[build]
  base = "."
  command = "npm run build"
  publish = "dist"

# Redirect API calls to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://tar-api-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Redirect WebSocket to Render backend
[[redirects]]
  from = "/ws"
  to = "https://tar-api-backend.onrender.com/ws"
  status = 200
  force = true

# SPA fallback - serve index.html for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff" 
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Environment variables for build
[build.environment]
  NODE_ENV = "production"
  API_URL = "https://tar-api-backend.onrender.com"
