databases:
  - name: tar-dashboard-db
    databaseName: tar_dashboard
    user: tar_admin
    region: singapore

services:
  # Main Web Service - Dashboard & API
  - type: web
    name: tar-dashboard-web
    env: python
    plan: starter
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python migration.py && uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 120"
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tar-dashboard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
      - key: AUTO_APPLY_ENHANCEMENTS
        value: "true"
      - key: SERVER_REGION
        value: "singapore"
      - key: CLOUDFRONT_BYPASS_REGION
        value: "sg"

  # Background Worker Service - Polling & Monitoring
  - type: worker
    name: tar-dashboard-worker
    env: python
    plan: starter
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "sleep 45 && python worker.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tar-dashboard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      - key: SERVER_REGION
        value: "singapore"
      - key: CLOUDFRONT_BYPASS_REGION
        value: "sg"

  # Strategy Monitor Service - Strategic Monitoring
  - type: worker
    name: tar-dashboard-strategy-monitor
    env: python
    plan: starter
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "sleep 60 && python init_strategy_monitor.py && python strategy_monitor_worker.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tar-dashboard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      - key: SERVER_REGION
        value: "singapore"
      - key: CLOUDFRONT_BYPASS_REGION
        value: "sg"


