services:
  - type: web
    name: tar-global-strategies-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET  
        generateValue: true
      - key: DEFAULT_TELEGRAM_BOT_TOKEN
        sync: false
      - key: DEFAULT_TELEGRAM_CHAT_ID
        sync: false
      - key: DEBUG
        value: "false"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"

databases:
  - name: tar-dashboard-db
    databaseName: tar_dashboard
    user: tar_admin

# Optional: Web service for database management (if needed)
# - type: web
#   name: tar-dashboard-admin
#   env: static
#   staticPublishPath: ./static
#   buildCommand: echo "Static admin panel"
#   routes:
#     - type: rewrite
#       source: /*
#       destination: /index.html
