# Updated: 2025-08-02T16:55:50.185446
databases:
  - name: tar-dashboard-db
    databaseName: tar_dashboard
    user: tar_admin
    region: singapore

services:
  # Main Web Service - Dashboard & API
  - type: web
    name: tar-dashboard-web
    env: python
    plan: starter
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "export PYTHONPATH=/opt/render/project/src && uvicorn app.main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 120"
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tar-dashboard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      - key: HOST
        value: "0.0.0.0"
      - key: AUTO_APPLY_ENHANCEMENTS
        value: "true"
      - key: SERVER_REGION
        value: "singapore"
      - key: CLOUDFRONT_BYPASS_REGION
        value: "sg"
      - key: SKIP_MIGRATIONS
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1"

  # Background Worker Service - Polling & Monitoring
  - type: worker
    name: tar-dashboard-worker
    env: python
    plan: starter
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "sleep 45 && export PYTHONPATH=/opt/render/project/src && python services/worker.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tar-dashboard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      - key: SERVER_REGION
        value: "singapore"
      - key: CLOUDFRONT_BYPASS_REGION
        value: "sg"

  # Strategy Monitor Service - Strategic Monitoring
  - type: worker
    name: tar-dashboard-strategy-monitor
    env: python
    plan: starter
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "sleep 60 && export PYTHONPATH=/opt/render/project/src && python utils/init_strategy_monitor.py && python services/strategy_monitor_worker.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tar-dashboard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      - key: SERVER_REGION
        value: "singapore"
      - key: CLOUDFRONT_BYPASS_REGION
        value: "sg"

  # Decter Engine Service - Internal Trading Bot Service
  - type: worker
    name: tar-dashboard-decter-engine
    env: python
    plan: starter
    region: singapore
    buildCommand: "pip install -r requirements.txt && pip install -r Decter/requirements.txt"
    startCommand: "sleep 90 && export PYTHONPATH=/opt/render/project/src && cd Decter && python main.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tar-dashboard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      - key: SERVER_REGION
        value: "singapore"
      - key: CLOUDFRONT_BYPASS_REGION
        value: "sg"
      - key: DECTER_ENGINE_NAME
        value: "Decter Engine (ACCU)"
      - key: DECTER_INTERNAL_MODE
        value: "true"
      - key: DATA_DIR
        value: "data"
      - key: PYTHONPATH
        value: "/opt/render/project/src:/opt/render/project/src/Decter"
      - key: PYTHONUNBUFFERED
        value: "1"


