services:
  - type: web
    name: tgl-medusa-loggers-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python migration.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tgl-medusa-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: APP_NAME
        value: TGL Medusa Loggers
      - key: DEBUG
        value: false
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /api/health

  - type: worker
    name: tgl-medusa-loggers-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tgl-medusa-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: APP_NAME
        value: TGL Medusa Loggers
      - key: DEBUG
        value: false
      - key: ENVIRONMENT
        value: production

databases:
  - name: tgl-medusa-db
    databaseName: tgl_medusa_loggers
    user: tgl_admin
    region: oregon
