services:
  # Main Web Service - Dashboard & API
  - type: web
    name: tar-dashboard-web
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt && python startup_migration.py && python pre_deployment_validation.py"
    startCommand: "python main.py"
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tar-dashboard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
      - key: AUTO_APPLY_ENHANCEMENTS
        value: "true"

  # Background Worker Service - Polling & Monitoring
  - type: worker
    name: tar-dashboard-worker
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tar-dashboard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"

  # Strategy Monitor Service - Strategic Monitoring
  - type: worker
    name: tar-dashboard-strategy-monitor
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_strategy_monitor.py && python strategy_monitor_worker.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tar-dashboard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"

databases:
  - name: tar-dashboard-db
    databaseName: tar_dashboard
    user: tar_admin
