services:
  - type: web
    name: tar-strategies-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "export PYTHONPATH=/opt/render/project/src && uvicorn app.main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 120"
    envVars:
      - key: SERVE_STATIC
        value: "true"
      - key: ENVIRONMENT
        value: "production"
    routes:
      - type: rewrite
        source: /*
        destination: /*