services:
  # Main Web Service - Dashboard & API
  - type: web
    name: tar-dashboard-web
    env: python
    plan: starter
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python startup_migration.py && python main.py"
    autoDeploy: true
    healthCheckPath: /api/health
    disk:
      name: tar-shared-db
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///data/medusa.db"  # Use shared persistent disk
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
      - key: AUTO_APPLY_ENHANCEMENTS
        value: "true"
      - key: SERVER_REGION
        value: "singapore"
      - key: CLOUDFRONT_BYPASS_REGION
        value: "sg"

  # Background Worker Service - Polling & Monitoring
  - type: worker
    name: tar-dashboard-worker
    env: python
    plan: starter
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    disk:
      name: tar-shared-db
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///data/medusa.db"  # Use shared persistent disk
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      - key: SERVER_REGION
        value: "singapore"
      - key: CLOUDFRONT_BYPASS_REGION
        value: "sg"

  # Strategy Monitor Service - Strategic Monitoring
  - type: worker
    name: tar-dashboard-strategy-monitor
    env: python
    plan: starter
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_strategy_monitor.py && python strategy_monitor_worker.py"
    disk:
      name: tar-shared-db
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///data/medusa.db"  # Use shared persistent disk
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: APP_NAME
        value: "TAR Global Strategies Dashboard"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
      - key: SERVER_REGION
        value: "singapore"
      - key: CLOUDFRONT_BYPASS_REGION
        value: "sg"
